#!/usr/bin/env python3
"""
Convert Adblock Plus filter rules to Clash/Mihomo domain format.

ABP syntax examples:
  ||example.com^              →  +.example.com
  ||example.com^$third-party  →  +.example.com
  ||example.com/path^         →  +.example.com  (strip path)
  ||*-wildcard*.example.com^  →  skip (wildcards unsupported)
  @@||example.com^            →  skip (whitelist)
  ! comment                   →  # comment
  /regex/                     →  skip (regex unsupported)

Output: one domain per line, +. prefix for domain-suffix matching.
"""

import re
import sys
from pathlib import Path


def convert_abp_to_clash(input_file: str, output_file: str, label: str = "") -> int:
    """Convert an ABP rules file to Clash domain format. Returns domain count."""
    domains: set[str] = set()
    skipped_wildcard = 0
    skipped_other = 0
    total_lines = 0
    abp_lines = 0

    with open(input_file, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            total_lines += 1
            line = line.strip()

            # Skip empty lines
            if not line:
                continue

            # Skip ABP comment/header lines
            if line.startswith("!") or line.startswith("["):
                continue

            # Skip whitelist (exception) rules
            if line.startswith("@@"):
                continue

            # Skip element hiding / cosmetic rules
            if "##" in line or "#?#" in line or "#@#" in line:
                skipped_other += 1
                continue

            # Skip raw regex rules
            if line.startswith("/") and line.endswith("/"):
                skipped_other += 1
                continue

            abp_lines += 1

            # --- Pattern 1: ||domain^  (most common, cleanest) ---
            m = re.match(r"^\|\|([^^/$*?]+)\^", line)
            if m:
                domain = m.group(1).strip().lower()
                if domain and "." in domain:
                    domains.add(domain)
                    continue

            # --- Pattern 2: ||domain^$options ---
            m = re.match(r"^\|\|([^^/$*?]+)\^\$.+", line)
            if m:
                domain = m.group(1).strip().lower()
                if domain and "." in domain:
                    domains.add(domain)
                    continue

            # --- Pattern 3: ||domain/path^  (strip path) ---
            m = re.match(r"^\|\|([^/^$*?]+)/", line)
            if m:
                domain = m.group(1).strip().lower()
                if domain and "." in domain:
                    domains.add(domain)
                    continue

            # --- Pattern 4: ||domain/path^$options ---
            m = re.match(r"^\|\|([^/^$*?]+)/.+\$.+", line)
            if m:
                domain = m.group(1).strip().lower()
                if domain and "." in domain:
                    domains.add(domain)
                    continue

            # --- Pattern 5: |https://domain^ or |http://domain^ ---
            m = re.match(r"^\|https?://([^^/$*?]+)\^", line)
            if m:
                domain = m.group(1).strip().lower()
                if domain and "." in domain:
                    domains.add(domain)
                    continue

            # --- Pattern 6: domain^ (no leading ||) ---
            m = re.match(r"^([a-z0-9][a-z0-9.-]+\.[a-z]{2,})\^", line)
            if m:
                domain = m.group(1).strip().lower()
                if domain and "." in domain and "*" not in domain:
                    domains.add(domain)
                    continue

            # Count what didn't match
            if "*" in line or "?" in line:
                skipped_wildcard += 1
            else:
                skipped_other += 1

    # Write Clash domain list
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(f"# {'HyperADRules' if not label else label} — Converted for Clash/Mihomo\n")
        f.write(f"# Source: {input_file}\n")
        f.write(f"# Total ABP rules processed: {abp_lines}\n")
        f.write(f"# Converted domains: {len(domains)}\n")
        f.write(f"# Skipped (wildcard): {skipped_wildcard}\n")
        f.write(f"# Skipped (other): {skipped_other}\n")
        f.write(f"# Total lines in source: {total_lines}\n")
        f.write(f"# Generated by convert_to_clash.py\n\n")
        for domain in sorted(domains):
            f.write(f"+.{domain}\n")

    print(
        f"[{label or input_file}] ABP rules: {abp_lines} → "
        f"domains: {len(domains)} "
        f"(skipped wildcard: {skipped_wildcard}, other: {skipped_other})"
    )
    return len(domains)


def main():
    files = {
        "rules.txt": "clash-domains.txt",
        "dns.txt": "clash-dns-domains.txt",
    }

    total = 0
    for src, dst in files.items():
        if Path(src).exists():
            count = convert_abp_to_clash(src, dst, label=src)
            total += count
            # Also show file size
            size_kb = Path(dst).stat().st_size / 1024
            print(f"  → Wrote {dst} ({size_kb:.0f} KB)")
        else:
            print(f"[SKIP] {src} not found, skipping")

    print(f"\nDone. Total unique domains across all files: (dedup per file)")

    # Create a combined deduplicated file
    if Path("clash-domains.txt").exists() or Path("clash-dns-domains.txt").exists():
        all_domains = set()
        for dst in files.values():
            if Path(dst).exists():
                with open(dst, "r", encoding="utf-8") as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith("#") and line.startswith("+."):
                            all_domains.add(line[2:])  # strip "+." prefix

        with open("clash-combined.txt", "w", encoding="utf-8") as f:
            f.write(f"# HyperADRules Combined — Clash/Mihomo domain-suffix list\n")
            f.write(f"# Merged from: {', '.join(files.values())}\n")
            f.write(f"# Total unique domains: {len(all_domains)}\n\n")
            for domain in sorted(all_domains):
                f.write(f"+.{domain}\n")

        size_kb = Path("clash-combined.txt").stat().st_size / 1024
        print(f"Combined: {len(all_domains)} unique domains → clash-combined.txt ({size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
